### ISSUE TITLE
pip installing MarkupSafe 0.0.0

### ISSUE THREAD

**Issue by ViRaL95** [pallets/markupsafe#267]
When installing markupsafe via pip, its installing version 0.0.0 instead of the latest version (version 2.0.1 at the time of writing this). Additionally I can not import markupsafe at all after performing the install. Im running pip 8.2.1 and python 2.7

Uninstalling markupsafe:

```
 python -m pip uninstall markupsafe
Uninstalling MarkupSafe-0.0.0:
  /usr/lib/python2.7/site-packages/MarkupSafe-0.0.0-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled MarkupSafe-0.0.0
You are using pip version 8.1.2, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Installing markupsafe:

```
python -m pip install markupsafe
Collecting markupsafe
  Using cached https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz
Installing collected packages: markupsafe
  Running setup.py install for markupsafe ... done
Successfully installed markupsafe-0.0.0
You are using pip version 8.1.2, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Importing markupsafe: 
```
python

Python 2.7.5 (default, Nov 16 2020, 22:23:17) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import markupsafe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named markupsafe
```

**Comment by ThiefMaster** [comment]
Don't use an ancient version of pip...

**Comment by davidism** [comment]
Python 2.7 is not supported upstream, we advise you to update your version of Python to at least 3.7 immediately to continue receiving support.

That version of pip is very old as well. Upgrade to the latest version of pip, which supports modern packaging metadata that will avoid this issue. If you cannot upgrade pip, specify the exact version of packages to install with `==`. Preferably, pin all dependencies in order to control what versions you install and test with.
