### ISSUE TITLE
Markup.striptags: comments now get replaced with a space

### ISSUE THREAD

**Issue by kholmanskikh** [pallets/markupsafe#417]
In 2.1.4, if `Markup.striptags` is called, the comment gets replaced by a space. In versions before that it's completely removed from the output.

Test case to reproduce:

```
import unittest

from markupsafe import Markup

class MarkupSafeTest(unittest.TestCase):
    def test_striptags(self):
        value = 'x <!-- comment -->'
        self.assertEqual(Markup(value).striptags(), 'x')


if __name__ == '__main__':
    unittest.main()
```

With markupsafe 2.1.4 it fails, with 2.1.3 - it passes.

I'm running with Python 3.11

The issue was originally found by running the `test_striptags` jinja test case with markupsafe 2.1.4:

https://github.com/pallets/jinja/blob/3fd91e4d11bdd131d8c12805177dbe74d85e7b82/tests/test_filters.py#L94

**Comment by dairiki** [comment]
I've just noticed this change, too.  I think the issue is that the old version of `Markup.striptags` removed comments and tags, _and then_ coalesced whitespace:

https://github.com/pallets/markupsafe/blob/496112e00fcfa54d81d256f1f7e221ad01d033cc/src/markupsafe/__init__.py#L165-L168

The new version has reversed this order and coalesces whitespace _before_ stripping comments and tags:

https://github.com/pallets/markupsafe/blob/b7cd6523579ea5a08d89799f2a64ec2c2bc45eca/src/markupsafe/__init__.py#L154-L170

(I think the old order of operations is correct.)
