### ISSUE TITLE
Publish plain-Python/'none-any' wheels 

### ISSUE THREAD

**Issue by mrpippy** [pallets/markupsafe#483]
It's great that markupsafe has a plain-Python option, but it would be more convenient if binary wheels of that configuration were published (on PyPI and GitHub).

[charset-normalizer](https://pypi.org/project/charset-normalizer/#files) is an example of a project that publishes both plain-Python/`none-any`, and binary wheels.

**Comment by davidism** [comment]
The no-speedup version is only intended for platforms that don't benefit from or can't build the speedups (pypy, graalpy). Otherwise, if a wheel isn't available, the speedups should still be built from sdist (for example, musl wheels weren't available until a few years ago, but the speedups could still be compiled on musl). If we provided a pure wheel, it would block building the speedups, which is not intended.
