### ISSUE TITLE
New release + wheel support?

### ISSUE THREAD

**Issue by barseghyanartur** [pallets/markupsafe#63]
Could you make a new release and add wheel support, please?

**Comment by barseghyanartur** [comment]
@davidism:

No comments?

**Comment by barseghyanartur** [comment]
@davidism:

FYI, I'm sending a mail to pallets project regarding your behaviour.

**Comment by davidism** [comment]
Asking for the release isn't going to make it happen faster, sorry. There's not really a point in keeping these types of requests open.

If you're able to provide a pull request that adds build support for Windows, Linux, and Mac, that will be helpful in getting wheel support going. Otherwise, I'll do this as I have time to.

**Comment by ThiefMaster** [comment]
Probably he closed it because it's a duplicate of #45

**Comment by barseghyanartur** [comment]
@davidism:

OK, but there are ways to say no. Closing the issue without leaving any remarks, removing my comments - that's pretty unsocial. And you're not even acting on your own but in this case on behalf of the whole pallets project. I hope you do realise it now. Thanks for your comment, finally.

@ThiefMaster: 

Clear. Thanks for your comment!
